NodeOUs:
    Enable: true
    ClientOUIdentifier:
      Certificate: cacerts/org3-ca-cert.pem
      OrganizationalUnitIdentifier: client
    PeerOUIdentifier:
      Certificate: cacerts/org3-ca-cert.pem
      OrganizationalUnitIdentifier: peer
  